### ISSUE TITLE
Reset/Remove User Account

### ISSUE THREAD

**Issue by NovaCyntax** [investbrainapp/investbrain#19]
Somehow used the wrong password when registering, and am now unable to log in. Deleted everything in the directory but it won't let me log in. I would just like to change the password or reset the account entirely, I was being a bit quick because I was excited to test it but now I can't find a way to reset it. Looking forward to adding this to my rotation so I can get stop using mobile apps.

**Comment by hackerESQ** [comment]
Hi @NovaCyntax,

Couple options: first you could delete all the containers and volumes and try again. Otherwise, you should be able to navigate to `/register` and create a new account. 

Unfortunately, without emails configured (typical for self-hosted environments) it's not really possible to reset your password. 

It may be useful in future to add a CLI method to reset passwords / manage users. But that's currently a low priority (focused on the investment tracker functionality). 

I'll close this issue, unless you have any other difficulties. 

Have fun!
