### ISSUE TITLE
Data Import: Replace Mode?

### ISSUE THREAD

**Issue by tynorton** [investbrainapp/investbrain#25]
Nice looking app so far, but I'm running into some friction while trying to test it.

**Problem**
I am incrementally migrating my available transaction data from several brokerages, and converting them into the investbrain import format. Each subsequent import of the xlsx file is additive and distorts all the data within the application. 

I would like to be able to maintain my own copy of the transaction data outside the application, and be able to re-import that (updated) data whenever.

**Question**
Is it possible to use import as a mechanism to replace the entire system of record (i.e. Transaction data)? If so, how can I do this? 

**Ask**
If not, the ask would be to add an option that would allow the user to treat the import as a "Replace" operation, wiping out existing transactional data (But maintaining the Portfolios). 

Import validation, history/audit log, and visual report of affected records would go a long way to aide in user clarity around that process as well. ;)

Cheers,
Ty

**Comment by hackerESQ** [comment]
Hi @tynorton the intended functionality is to do an "upsert" while importing.

When the 'id' column is blank, it should be importing your transactions and portfolios. 

If there is an 'id' listed, will find the matching portfolio or transaction and update it. 

I'm working on clarifying this in the docs. Hope this helps?

If you're not experiencing the expected behavior, please share some before and after exports so I can see what's going on.
